spring:
  application:
    name: weather
  cache:
    type: simple

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

openweathermap:
  api-url: https://api.openweathermap.org/data/2.5/weather
  api-key: ${OPENWEATHERMAP_API_KEY}
